[project]
name = "exam"
version = "0.1.0"
description = "Exam build using TeXSmith."
requires-python = ">=3.13"
dependencies = [
    "texsmith>=0.6,<1.0",
    "texsmith-template-exam",
]

[project.optional-dependencies]
dev = [
    "PyYAML>=6.0,<7.0",
]

[tool.uv.sources]
texsmith = { git = "https://github.com/yves-chevallier/texsmith.git" }
texsmith-template-exam = { path = "/home/ycr/template-exam", editable = true }
