title: "SÃ©rie 23"
subtitle: "Les pointeurs"
language: fr
typesetting:
  paragraph:
    indent: none
    spacing: 1.1em
press:
  paper:
    margin:
      top: 12mm
      left: 2.4cm
      right: 2.4cm
      bottom: 2.4cm
    marks: false
exam:
  course: INFO2-TIN
  titlepage: minimal
