title: "SÃ©rie 9"
subtitle: "Pointeurs et tableaux"
language: fr
typesetting:
  paragraph:
    indent: none
    spacing: 1.1em
press:
  paper:
    margin:
      top: 12mm
      left: 2.4cm
      right: 2.4cm
      bottom: 2.4cm
    marks: false
exam:
  course: INFO1-TIN
  titlepage: minimal
